CREATE TABLE IF NOT EXISTS players (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    x DOUBLE PRECISION NOT NULL DEFAULT 320,
    y DOUBLE PRECISION NOT NULL DEFAULT 260,
    hp INTEGER NOT NULL DEFAULT 100,
    max_hp INTEGER NOT NULL DEFAULT 100,
    level INTEGER NOT NULL DEFAULT 1,
    xp INTEGER NOT NULL DEFAULT 0,
    credits INTEGER NOT NULL DEFAULT 100,
    inventory JSONB NOT NULL DEFAULT '[]'::jsonb,
    quest_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
